export const ESPECIALIDADES_MEDICAS = [
  "Anestesiologia",
  "Cardiologia",
  "Cardiologia Pediátrica",
  "Cirurgia Cardiotorácica",
  "Cirurgia Geral",
  "Cirurgia Ortopédica",
  "Cirurgia Pediátrica",
  "Cirurgia Plástica e Reconstrutiva",
  "Cirurgia Vascular",
  "Clínica Geral",
  "Dermatologia",
  "Endocrinologia",
  "Gastroenterologia",
  "Geriatria",
  "Ginecologia e Obstetrícia",
  "Hematologia",
  "Imunologia",
  "Infectologia",
  "Medicina de Emergência",
  "Medicina Desportiva",
  "Medicina do Trabalho",
  "Medicina Interna",
  "Medicina Legal",
  "Medicina Paliativa",
  "Neonatologia",
  "Nefrologia",
  "Neurologia",
  "Neurocirurgia",
  "Oftalmologia",
  "Oncologia",
  "Ortopedia e Traumatologia",
  "Otorrinolaringologia",
  "Patologia Clínica",
  "Pediatria",
  "Pneumologia",
  "Psiquiatria",
  "Radiologia",
  "Reumatologia",
  "Urologia",
] as const;

export type Especialidade = (typeof ESPECIALIDADES_MEDICAS)[number];

export const ESPECIALIDADES_ENFERMAGEM = [
  "Enfermagem Geral",
  "Enfermagem de Urgência e Emergência",
  "Enfermagem de Cuidados Intensivos",
  "Enfermagem Pediátrica",
  "Enfermagem Obstétrica",
  "Enfermagem de Saúde Mental",
  "Enfermagem Oncológica",
  "Enfermagem Cirúrgica",
] as const;

export const TODAS_ESPECIALIDADES = [
  ...ESPECIALIDADES_MEDICAS,
  ...ESPECIALIDADES_ENFERMAGEM,
] as const;
